name: Rector

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rector:
    strategy:
      matrix:
        php-version: ['8.5']
    uses: openCoreEMR/github-workflows-public/.github/workflows/php-composer-script.yml@1.0.0
    with:
      name: Run Rector (dry-run)
      php-version: ${{ matrix.php-version }}
      run: composer rector
